# Generated by Django 5.0.3 on 2024-03-23 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100, null=True)),
                ('section', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_in_arabic', models.CharField(max_length=100)),
                ('name_in_english', models.CharField(max_length=100)),
                ('job_title_arabic', models.CharField(max_length=100, null=True)),
                ('job_title_english', models.CharField(max_length=100, null=True)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widow', 'Widow')], max_length=50, null=True)),
                ('religion', models.CharField(choices=[('Muslim', 'Muslim'), ('Christian', 'Christian')], max_length=50, null=True)),
                ('national_id', models.CharField(max_length=14, null=True)),
                ('expire_date', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('place_of_birth', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.TextField(null=True)),
                ('work_phone', models.CharField(max_length=20, null=True)),
                ('mobile_no', models.CharField(max_length=20, null=True)),
                ('education', models.CharField(max_length=100, null=True)),
                ('military_status', models.CharField(max_length=50, null=True)),
                ('join_date', models.DateField(null=True)),
                ('hiring_date', models.DateField(null=True)),
                ('contract_type', models.CharField(max_length=100, null=True)),
                ('contract_start_date', models.DateField(null=True)),
                ('contract_end_date', models.DateField(null=True)),
                ('bank_name', models.CharField(max_length=100, null=True)),
                ('bank_account_no', models.CharField(max_length=100, null=True)),
                ('insurance_type', models.CharField(max_length=100, null=True)),
                ('insurance_no', models.CharField(max_length=100, null=True)),
                ('insurance_branch', models.CharField(max_length=100, null=True)),
                ('private_health_insurance', models.BooleanField(null=True)),
                ('previous_insurance_years', models.IntegerField(null=True)),
                ('previous_insurance_months', models.IntegerField(null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.department')),
                ('direct_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='department_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_department', to='employee.employee'),
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('employee.employee',),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('employee.employee',),
        ),
        migrations.CreateModel(
            name='InsuranceInformation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('employee.employee',),
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('employee.employee',),
        ),
    ]
